### ISSUE TITLE
Support `bz2` source archive

### ISSUE THREAD

**Issue by sir4ur0n** [balsoft/opam-nix#100]
**Is your feature request related to a problem? Please describe.**
Have an Opam file depend on `ocaml-version.3.7.1` (https://opam.ocaml.org/packages/ocaml-version/ocaml-version.3.7.1/).
`opam-nix` crashes with this error:
```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/hk2v8584dqhsa6vb9d624zzmwka1vbvi-ocaml-version-3.7.1.bz2
do not know how to unpack source archive /nix/store/hk2v8584dqhsa6vb9d624zzmwka1vbvi-ocaml-version-3.7.1.bz2
```

**Describe the solution you'd like**
Support `.bz2` source archive formats.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by balsoft** [comment]
Can you check if it works with d464d52 ?

**Comment by sir4ur0n** [comment]
I couldn't directly check with this commit because of https://github.com/tweag/opam-nix/issues/99 but I tried by cherry-picking https://github.com/tweag/opam-nix/commit/d464d52bdb879c4e943c8ac5f20e01465d6fdfd5 on top of `main`: https://github.com/sir4ur0n/opam-nix/commit/1ef3623fd23a06e37fbb4cae41971d7d880b1953

The error is the same:
```
error: builder for '/nix/store/28wf7i3bfmw0cwqv5h1wknsgbs7hxbkg-ocaml-version-3.7.1.drv' failed with exit code 1;
       last 3 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/hk2v8584dqhsa6vb9d624zzmwka1vbvi-ocaml-version-3.7.1.bz2
       > do not know how to unpack source archive /nix/store/hk2v8584dqhsa6vb9d624zzmwka1vbvi-ocaml-version-3.7.1.bz2
       For full logs, run 'nix log /nix/store/28wf7i3bfmw0cwqv5h1wknsgbs7hxbkg-ocaml-version-3.7.1.drv'.
error: 1 dependencies of derivation '/nix/store/nrk07mq50pmqxjq33sq2mfhk6q5b070i-mdx-2.4.1.drv' failed to build
error (ignored): error: cannot unlink '"/tmp/nix-build-re-1.12.0.drv-2/build/re-1.12.0/_build"': Directory not empty
error: 1 dependencies of derivation '/nix/store/jgc60rcfc881qd8inkdy6lspc5n02zlb-nix-shell-env.drv' failed to build
```

**Comment by balsoft** [comment]
Took some time to debug it, found the proper solution. `ocaml-version-3.7.1` builds now.

**Comment by sir4ur0n** [comment]
I confirm it works with the latest commit on `main`, thank you :pray:
