### ISSUE TITLE
pyml-20231101 - fails to install with unpacker error

### ISSUE THREAD

**Issue by aqxa1** [balsoft/opam-nix#103]
**Describe the bug**
pyml ocaml package fails to install during unpack phase

nix log /nix/store/465ma9n6f1xs92vf6br13hp37czpbzba-pyml-20231101.drv:
```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/9dclwgb7a1grignvcafcmxq7l3wvgn91-pyml.20231101.tar.gz
unpacker appears to have produced no directories
```

**To Reproduce**
Build a program that depends on pyml with latest opam-nix (built on 08-12-2024)

**Expected behavior**
Program should build and install.

**Environment**
 - OS name + version: Nixos-unstable
 - Version of the code: pyml-20231101, latest opam-nix

**Additional context**
Regression. Doesn't occur with previous flake (updated on 30-11-2024).

**Comment by balsoft** [comment]
I think this is because pyml produced an incorrect source archive, it has all the files at the top-level. I'll fix it.

**Comment by balsoft** [comment]
Thanks for raising this!
