### ISSUE TITLE
Pin-depends do not work for packages outside of opam repository.

### ISSUE THREAD

**Issue by rizo** [balsoft/opam-nix#2]
**Describe the bug**
It seems that the pin-depends feature implemented in opam-nix is currently only implemented as an override for packages that are already part of the official opam repository. The same functionality in opam allows to pin packages that are not part of the opam repository and I think similar treatment should be implemented in opam-nix.

**To Reproduce**

1. Create an opam file with a pin-depends section containing a package that is _not_ part of the opam repository.
2. Use `buildOpamProject` or `buildDuneProject` with `pinDepends = true`.
3. Build the project and confirm the error (where the pinned package is called `options` in my case).

```
error: builder for '/nix/store/hd1mg3ylzq7j7v6psc867dlnvrjdh260-resolve.drv' failed with exit code 20;
       > [ERROR] No solution including optional dependencies for fmt & hello.dev:   * Missing dependency:
       >             - options
       >             unknown package
```

See the files below that can reproduce the described issue.

<details>
<summary>  <code>flake.nix</code></summary>

```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/21.11";
    flake-utils.url = "github:numtide/flake-utils";
    nix-filter.url = "github:numtide/nix-filter";
    opam-nix.url = "path:./opam-nix";
  };
  outputs = { self, nixpkgs, flake-utils, nix-filter, opam-nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        src = nix-filter.lib.filter {
          root = ./.;
          include = [
            "dune-project"
            "hello.opam"
            (nix-filter.lib.inDirectory "hello")
          ];
        };
        scope = opam-nix.lib.${system}.buildOpamProject {
          inherit pkgs;
          pinDepends = true;
        } "hello" src { fmt = null; };

      in rec {
        defaultPackage = scope.hello;
        defaultApp = flake-utils.lib.mkApp { drv = defaultPackage; };
        devShell = pkgs.mkShell {
          nativeBuildInputs = defaultPackage.nativeBuildInputs;
        };
      });
}
```
</details>

<details>
<summary><code>hello.opam</code></summary>

```
opam-version: "2.0"
build: [ ["dune" "build" "-p" name] ]
depends: [
  "ocaml" {= "4.13.1"}
  "dune" {build}
  "fmt"
  "options"
]
pin-depends: [
   ["options.dev" "git+https://github.com/odis-labs/options.git#master"]
]
```
</details>

**Expected behavior**
The expected behavior is for any kind of opam project outside of opam repository to be included in the resolution and build process.

**Environment**
 - OS name + version: macOS 12.0.1 arm64
 - Version of the code: `272fdbc` (latest commit)

**Additional context**
From my cursory look at the code in `opam.nix` the issue seems to be that:

- in `buildOpamProject` the `pinDepsOverlay` is added to overlays for `queryToScope`;
- in `queryToScope` the overlays (containing pin deps) are applied after the resolution happens.

I think the potential solution could be expanding all `pin-depends` into separate repositories with `makeOpamRepo` and adding the pins to `repos`, instead of overlays.

**Comment by balsoft** [comment]
Yep, this makes sense. I'll see if I can fix this.

**Comment by rizo** [comment]
Thanks for the quick reply!

I made a small patch that implements my suggestion for `buildOpamProject` (but not `buildOpamProject'`): https://github.com/rizo/opam-nix/commit/776a889e211aa63799291f26d2ff85c1fff15629. Happy to submit a more complete PR, if that helps.

**Comment by balsoft** [comment]
Please do! It has a small issue, but that's better than not supporting pin-depends at all :)

**Comment by balsoft** [comment]
Figured out a slightly better way to do it & implemented it. Thanks for bringing the issue to my attention!

**Comment by rizo** [comment]
Thanks, @balsoft!

Apologies for not submitting my changes – I got stuck testing a few other edge-cases with pin-depends and wanted to get back to you with more details.

To give you some context, I'm currently migrating a medium-sized project to opam-nix where pin-depends are used extensively for adding patches to upstream projects as well as using unreleased new projects.

Below is an overview of a few issues I've encountered so far with the [current](https://github.com/tweag/opam-nix/commit/5a9c0e09e76d5fd0a7bf21ac70cb44f5dbf2290b) pin-depends implementation. I can, of course, open separate issues with more details, or discuss them here – just let me know your preference.

### 1. `builtins.fetchTree` does not fetch the correct revisions

Specifically, from my observations, `fetchTree`, used to obtain pin-depends sources, will simply ignore the revision provided in the URI and will always fetch the latest master commit (alas, without any warnings).

See a REPL session below that demonstrates differences in expected and actual `rev`s where:

- `streaming.git#74a48634f81eefc5ff98103016b4be9645c1ea01` is the latest master commit (`fetchTree` _appears_ to be working correctly).
- `digestif.git#ecee3ed464a62b9f96be1eaf81d5bcdde53d8e6c` is an old commit from from the master branch.
- `ppx_rapper#04c6ca097b2abd7dccbfe3311db075e0f9c60906` is a commit from from a non-master branch.

```
nix-repl> builtins.fetchTree "git+https://github.com/odis-labs/streaming.git#74a48634f81eefc5ff98103016b4be9645c1ea01"
{ ... rev = "74a48634f81eefc5ff98103016b4be9645c1ea01"; ... }

nix-repl> builtins.fetchTree "git+https://github.com/Nymphium/digestif.git#ecee3ed464a62b9f96be1eaf81d5bcdde53d8e6c"   
{ ... rev = "2e67e5512527f9c6286d879352d6999b83e6bf5f"; ... }

nix-repl> builtins.fetchTree "git+https://github.com/hyper-systems/ppx_rapper#04c6ca097b2abd7dccbfe3311db075e0f9c60906"
{ ... rev = "41a180a1f6f7e52af3fcd1a7573e192c25a0901b"; ... }
```

I know I should probably report this upstream, but I reckon it's easier to find a workaround for opam-nix in the meantime.

I did some testing and it seems we could use `builtins.fetchGit` for this:

```
nix-repl> builtins.fetchGit {url="https://github.com/ocaml/dune.git"; rev= "82102aba39c2a4073cd244e0e24b591dad027952"; allRefs = true; }
{ ... rev = "82102aba39c2a4073cd244e0e24b591dad027952"; ... }
```

I tested this with the following patch in `opam.nix` in the `getPinDepends` function:

```nix
let
  fullUrl = (last dep); # get the pin-depend entry url
  baseUrl = last (splitString "+" fullUrl); # Get rid of "git+"
  urlParts = splitString "#" baseUrl;
  path = builtins.fetchGit {
    url = head urlParts;
    rev = last urlParts;
    allRefs = true;
  };
```

There's probably a better way to parse the URI, but it works! Note that this also works for repositories with non-master default branches being a viable workaround for https://github.com/tweag/opam-nix/issues/1#issuecomment-1008632711.


### 2. `makeOpamRepo` attempts to find `.opam` in sub-directories

I understand this was likely an intentional choice, but it seems at odds with the conventions used by opam itself, dune and tools like [opam monrepo](https://github.com/ocamllabs/opam-monorepo) that will only lookup opam files in the root folder.

This is problematic because, for example, when I tried to pin `git+https://github.com/ocaml/dune.git#82102aba39c2a4073cd244e0e24b591dad027952` the compilation fails because a random opam file from a test directory is loaded by opam-nix.

Replacing `readDirRecursive` with `readDir` in `makeOpamRepo` seems to solve this issue.


### 3. Incorrect resolution with the `ppx_rapper` pin-depend

This is a weird one and I need to investigate this further, but I figured I'd mentioned it here.

A pin-depends entry shown below (using the fixes to fetch the correct URI described above), will not be added to the opam scope and an upstream opam-repository package will be used instead. Specifically, `scope.ppx_rapper.src` is something like `/nix/store/vbkylx5jgg53lnp4h3r9fqwbysizy44b-3.0.0.tar.gz` which is the tarball from the upstream opam file.

```
pin-depends: [
  ["ppx_rapper.dev" "git+https://github.com/hyper-systems/ppx_rapper#04c6ca097b2abd7dccbfe3311db075e0f9c60906"]
]
```

This only happens to this particular git repository, and I currently don't understand why. But... if I remove the call to `filterOpamRepo` in `getPinDepends` the resolution works as expected!

---

Sorry for dumping so much information here, let me know if I should open separate issues. I hope you find this useful and I'd be glad to help fixing, reviewing and testing these issues further.

And thanks for writing such a nice tool, I look forward to using it my projects!

**Comment by balsoft** [comment]
Thanks for reporting all these! I'll apply the patches for (1) and (2) from your branch: https://github.com/hyper-systems/opam-nix/commits/hyper-master and also see what's going on with (3).

**Comment by rizo** [comment]
Thanks a lot, @balsoft! 

Re 3: It seems that `filterOpamRepo` will create a broken symlink for the pin package in the repo.

**Comment by balsoft** [comment]
It looks like the problem is that ppx_rapper specifies `3.0.0` as its version: https://github.com/hyper-systems/ppx_rapper/blob/04c6ca097b2abd7dccbfe3311db075e0f9c60906/ppx_rapper.opam#L3 but the pin-depends tries to get `ppx_rapper.dev` from there. I think I misunderstood the semantics of pin-depends.

**Comment by balsoft** [comment]
Looks like it pulls the right one now with https://github.com/tweag/opam-nix/commit/e47beb44b5568bb065f272b806443c78b9aa2ff2

**Comment by rizo** [comment]
@balsoft That's excellent, thank you! Yes, with pin-depends, the version should always be just `dev`.
