### ISSUE TITLE
compareVersions' does not correctly handle versions containing `~`.

### ISSUE THREAD

**Issue by SquidDev** [balsoft/opam-nix#21]
**Describe the bug**
When finding the list of input OCaml packages for a derivation, ocaml-nix attempts to compare version constraints with the `compareVersions'` function.

However this function does not quite match opam's behaviour for packages containing `~`: opam treats `~` as smaller than `~beta`, but opam-nix treats it as larger. This means that a dependency may show up in opam's solution, but will not be added as a build dependency in the actual nix derivation.

This was encountered when trying to depend on OCaml 5.0.0~alpha1. This [specifies a version bound of `>= 5.0.0~ && < 5.0.1~`](https://github.com/ocaml/opam-repository/blob/master/packages/ocaml/ocaml.5.0.0/opam), but `5.0.0~alpha1` is treated as smaller than `5.0.0~` by opam-nix.

**To Reproduce**
[There's an expected ordering of versions on the opam manual](https://opam.ocaml.org/doc/Manual.html#version-ordering), which we can compare against opam-nix's behaviour:

```nix
let 
  actual =  (builtins.sort (compareVersions' "lt")
    ["0.1" "1.0-test" "1.0.1" "1.0.10" "1.0" "1.0~beta" "dev" "trunk" "~" "~~" "~beta10" "~beta2"]);
  exp = ["~~" "~" "~beta2" "~beta10" "0.1" "1.0~beta" "1.0" "1.0-test" "1.0.1" "1.0.10" "dev" "trunk"]; 
in
if actual != exp then 
  builtins.throw "Expected: ${builtins.concatStringsSep ", " exp}\nActual:   ${builtins.concatStringsSep ", " actual}"
else
  true

# error: Expected: ~~, ~, ~beta2, ~beta10, 0.1, 1.0~beta, 1.0, 1.0-test, 1.0.1, 1.0.10, dev, trunk
#        Actual:   ~beta2, ~beta10, 0.1, 1.0, 1.0-test, 1.0~beta, 1.0.1, 1.0.10, dev, trunk, ~~, ~
```

In the case of building OCaml, running `nix build` with the following crate:

<details><summary>flake.nix</summary>

```nix
{
  description = "A very basic flake";

  inputs.opam-nix.url = "github:tweag/opam-nix";
  inputs.opam-repository = { url = "github:ocaml/opam-repository"; flake = false; };
  inputs.ocaml-beta-repository = { url = "github:ocaml/ocaml-beta-repository"; flake = false; };

  outputs = { self, opam-nix, opam-repository, ocaml-beta-repository }:
    let 
      system = "x86_64-linux";
      inherit (opam-nix.lib.${system}) queryToScope;
      scope = queryToScope { repos = [ocaml-beta-repository opam-repository]; } { 
        ocaml = "5.0.0";
        ocaml-base-compiler = "*";
      };
    in
    {
      defaultPackage.x86_64-linux = scope.ocaml;
    };
}
```

</details>

fails when building the `ocaml` opam package with the error: `ocaml: command not found`, as `opam-base-compiler` is never added as a dependency!

**Expected behavior**
I'd expect the behaviour to exactly match opam.

**Environment**
 - OS name + version:
 - Version of the code: ea5924dcde987f116719d9a0083f44d87b4010d0

**Additional context**
I'm happy to have a look at fixing this if preferred, just wanted to raise this first to discuss possible solutions.

The most comprehensive option would of course just be to port [opam's version comparison implementation](https://github.com/ocaml/opam/blob/master/src/core/opamVersionCompare.ml) to nix, but not sure if that's a little overkill? (and is licenced under the LGPL, which may not be acceptable for you).

**Comment by balsoft** [comment]
Ah, yes, I've been afraid that I had messed it up somewhere :( I think it is best to reimplement the algorithm ourselves more correctly, without porting it directly (since that would be LGPL license violation).

**Comment by balsoft** [comment]
Should be fixed now. Please confirm.

**Comment by SquidDev** [comment]
Yes, that appears to work! Thank you so much.
