### ISSUE TITLE
opam package coq-of-ocaml not working

### ISSUE THREAD

**Issue by Alizter** [balsoft/opam-nix#33]
**Describe the bug**
Building an opam-nix derivation with coq-of-ocaml doesn't work.

**To Reproduce**
Add coq-of-ocaml to the dev deps of an opam nix build.

**Expected behavior**
For the package to work.

**Additional context**
```
error: builder for '/nix/store/xn35ysz8r9kwvyd51yir61vdy0mhpsw2-coq-of-ocaml-2.5.3+4.14.drv' failed with exit code 1;
       last 3 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/47888vypivqxqgjkhk3kfz3fhrah6yw3-coq-of-ocaml-full.2.5.3+4.14.tar.gz
       > unpacker produced multiple directories
       For full logs, run 'nix log /nix/store/xn35ysz8r9kwvyd51yir61vdy0mhpsw2-coq-of-ocaml-2.5.3+4.14.drv'.
error: 1 dependencies of derivation '/nix/store/zlkvpv32nb6gi7n0vb2vs71cnim5hspg-nix-shell-env.drv' failed to build
```

**Comment by Alizter** [comment]
This is a new opam package, so make sure to update your opam repo when testing.

**Comment by balsoft** [comment]
Looks like the package source is a tarball with multiple directories (which is a bad practice). I'll fix it with an override, but ideally it should be fixed upstream by providing a properly generated tarball.
