### ISSUE TITLE
Naive failure from flake init templates?

### ISSUE THREAD

**Issue by AlexMouton** [balsoft/opam-nix#36]
**Describe the bug**
Hi Folks.
Hoping its just me, but running the flake init command, changing the package string, I next get:
```
error: attribute '<package-name>' missing

       at /nix/store/b39yb2zy2ikm70yicc9i029xknhh6wjj-source/flake.nix:31:24:

           30|           # You can add overrides here
           31|           ${package} = prev.${package}.overrideAttrs (_: {
```               

**To Reproduce**
nix flake init -t github:tweag/opam-nix#executable
<change package name>
nix develop

**Environment**
 - OS name + version: nixos-unstable w nix 2.11.1
 - Version of the code: unsure.

**Comment by balsoft** [comment]
What did you change the package name to?

It seems to work on my end.

**Comment by AlexMouton** [comment]
let package = "aaa";

**Comment by balsoft** [comment]
Is there a corresponding `aaa.opam` file? (or an `opam` file with `name: "aaa"`)

**Comment by AlexMouton** [comment]
ah nope. i was trying to start from zero.
Thats likely my problem. thanks!

**Comment by balsoft** [comment]
Yeah, the templates are for packaging an already existing opam package. I think that fact should be mentioned somewhere :)

**Comment by AlexMouton** [comment]
The group of people that have heard of ocaml and nix but used neither may be your largest audience in the short term =)

Thanks for your time

**Comment by balsoft** [comment]
I have added a note about this in the README: https://github.com/tweag/opam-nix/commit/4bb1a4c372f639f44fc6745f13c86f4397e82d34
