### ISSUE TITLE
Static Binaries

### ISSUE THREAD

**Issue by solomon-b** [balsoft/opam-nix#45]
**Is your feature request related to a problem? Please describe.**

I need to produce a static build of an ocaml project for deployment purposes.

**Describe the solution you'd like**

It would be really cool if we could do this with opam-nix and musl.

**Describe alternatives you've considered**

I'm not very familiar with ocaml tooling but it looks like the alternative is to try to use dune a la this blog post:
https://ocamlpro.com/blog/2021_09_02_generating_static_and_portable_executables_with_ocaml/

**Additional context**

**Comment by balsoft** [comment]
You can totally do that with `opam-nix`! There are even a couple of examples that might help you get started:

- [Building a static version of a package using compiler from nixpkgs](https://github.com/tweag/opam-nix/blob/main/examples/opam-ed/flake.nix)
- [Building a static version of a package using the compiler from opam](https://github.com/tweag/opam-nix/blob/main/examples/opam2json-static/flake.nix)

If you can't get it to work for your use-case, please open separate issues.

**Comment by solomon-b** [comment]
Oh wow thank you!
