### ISSUE TITLE
Installing an old version of Coq via opam-nix fails, related to coq-stdlib

### ISSUE THREAD

**Issue by Coda-Coda** [balsoft/opam-nix#48]
**Describe the bug**
Old versions of Coq listed in an opam file fail to install, likely due to: 5bfdc95cfb7662cac808eb1baa70ae3fff0cab4f [ocaml.nix - line 133](https://github.com/tweag/opam-nix/commit/5bfdc95cfb7662cac808eb1baa70ae3fff0cab4f#diff-3455905101d444228466115e49f6a36d39bd4cdd9b5cae403c0f6e52ffa740f9R133) and that [coq-stdlib](https://ocaml.org/p/coq-stdlib/8.17.1) is only for newer versions of Coq.

**To Reproduce**
An opam file with: `"coq" {>= "8.10" & < "8.11.0" }` fails to build when following the standard instructions in the README of opam-nix with the error: `error: attribute 'coq-stdlib' missing`.

It seems that `coq-of-ocaml` is possibly meant as an alternative to writing `coq`. Using this still does not work, giving the error `No agreement on the version of coq-of-ocaml`.

(Using `nix develop` to trigger a build of Coq).

**Expected behavior**
An opam file with `"coq" {>= "8.10" & < "8.11.0" }` would succeed at building Coq following the instructions of the README.

**Environment**
 - OS name + version: NixOS
 - Version of the code: 5bfdc95cfb7662cac808eb1baa70ae3fff0cab4f

**Additional context**
Reverting 5bfdc95cfb7662cac808eb1baa70ae3fff0cab4f fixes the issue.

**Comment by balsoft** [comment]
Hi, thanks for reporting!

Should be fixed now. Could you confirm and reopen otherwise?

**Comment by Coda-Coda** [comment]
Hi @balsoft, thanks for the fix! Yes I can confirm that does fix this issue. However, I've now raised #49 which is related. I did try to fix it myself but was not able to.
