### ISSUE TITLE
Missing dependency with non-trivial formula

### ISSUE THREAD

**Issue by madidier** [balsoft/opam-nix#55]
**Describe the bug**

Building ocamlformat-lib 0.26.1 fails because the ocp-indent dependency is missing at build time.
The opam file from opam-repository lists the dependency as:

- `"ocp-indent" {with-test = "false" & >= "1.8.0" | with-test & >= "1.8.1"}`

**To Reproduce**

You can use the following flake:

```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    opam-nix.url = "github:tweag/opam-nix";
    opam-repository = {
      url = "github:ocaml/opam-repository";
      flake = false;
    };
  };

  outputs = { self, flake-utils, opam-nix, opam-repository }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        scope =
          opam-nix.lib.${system}.queryToScope { repos = [ opam-repository ]; } {
            ocamlformat-lib = "*";
            ocaml-base-compiler = "5.1.0";
          };
      in {
        legacyPackages = scope;
        defaultPackage = scope.ocamlformat-lib;
      });
}
```

It is possible to workaround this by vendoring opam-repository and replacing the problematic line to one with a simpler formula.

I achieved this with a folder with the following structure in my project:

```
opam-repo-overrides/
├── packages
│   └── ocamlformat-lib
│       └── ocamlformat-lib.0.26.1
│           └── opam
├── README
└── repo
```

The opam file there is a copy of `opam-repository`'s, with the formula simplified to `{>= "1.8.1"}`.

**Comment by balsoft** [comment]
Hi! Fixed now. Thanks a lot for the report <3
