### ISSUE TITLE
argon2 leads to infinite recursion

### ISSUE THREAD

**Issue by sheridanchris** [balsoft/opam-nix#56]
**Describe the bug**
`argon2` fails to install and results in an infinite recursion error.

**To Reproduce**
`nix shell github:tweag/opam-nix#argon2.latest`

**Expected behavior**
The `argon2` derivation should work properly. 

**Environment**
 - OS name + version: NixOS 23.11.20230929.f5892dd (Tapir)
 - Version of the code: latest

**Comment by balsoft** [comment]
Fixed in 778f91cbf4ead8ab990db98dc2430bf65afca326
