### ISSUE TITLE
Why dontPatchShebangsEarly?

### ISSUE THREAD

**Issue by rizo** [balsoft/opam-nix#7]
This is more of a question than an issue but why does opam-nix use [`dontPatchShebangsEarly`](https://github.com/tweag/opam-nix/blob/587b3fc54ba506f7764712c2d924beea2dfac7f4/src/builder.nix#L220) instead of a more common name [`dontPatchShebangs`](https://ryantm.github.io/nixpkgs/stdenv/stdenv/#var-stdenv-dontPatchShebangs)?

As part of our build process we run `dune subst` which will invoke git to obtain the current revision, setting `dontPatchShebangsEarly` is important to avoid the `-dirty` suffix in the version. I spent a few hours debugging this until realised that the builder in opam-nix does not use `dontPatchShebangs`.

**Comment by balsoft** [comment]
`stdenv` only applies `patchShebangs` to the output of the derivation during `fixupPhase`, while we need to run it on the derivation source during the `configurePhase`. However, it is important that we can disable it (for cases like yours), so it is controlled with `dontPatchShebangsEarly` :)

**Comment by rizo** [comment]
Oh, I see. I didn't know that `patchShebangs` was applied after, but I guess it makes sense.
