### ISSUE TITLE
Handle ocaml stublibs properly

### ISSUE THREAD

**Issue by rvem** [balsoft/opam-nix#9]
**Is your feature request related to a problem? Please describe.**

Currently, `opam-nix` installs ocaml stublibs to `$OCAMLFIND_DESTDIR/${pname}` together with the rest of the libraries.
However,  ocaml compiler expects them to be present in `$OCAMLFIND_DESTDIR/stublibs` directory.

This is the case for e.g. `zarith` library.

**Describe the solution you'd like**

The following `postInstall` workaround seems to work:
```
postInstall = ''
    mkdir -p "$OCAMLFIND_DESTDIR/stublibs"
    ln -s "$OCAMLFIND_DESTDIR"/${o.pname}/dll*.so "$OCAMLFIND_DESTDIR"/stublibs/
  '';
```

Ideally, `opam-nix` should handle this automatically. Maybe there is a way to specify a place to looks for stublibs.

**Comment by balsoft** [comment]
`opam-nix` just calls `make install` in case of zarith, which then calls `ocamlfind install`. That doens't seem to install stuff correctly for some reason.

**Comment by balsoft** [comment]
Ok, I see. `ocamlfind install` will only install DLLs to `stublibs` if that directory exists.

**Comment by balsoft** [comment]
Thanks!
