### ISSUE TITLE
Support `git://` URLs

### ISSUE THREAD

**Issue by sir4ur0n** [balsoft/opam-nix#99]
**Is your feature request related to a problem? Please describe.**
Currently `opam-nix` seems to support `git+ssh://` URLs but not `git://` URLs.

**Describe the solution you'd like**
Support `git://` URLs.

**Describe alternatives you've considered**
Currently we maintain a fork of `opam-nix` with an extra commit to add best-effort support for such URLs, in case that helps:
```diff
diff --git a/src/evaluator/default.nix b/src/evaluator/default.nix
index de92f4e..25cb272 100644
--- a/src/evaluator/default.nix
+++ b/src/evaluator/default.nix
@@ -458,6 +458,7 @@ in rec {
       optionalRev = optionalAttrs hasRev { rev = ref; };
       refsOrWarn = if hasRef && !isRev ref then {
         inherit ref;
+        allRefs = true;
       } else if lib.versionAtLeast nixVersion "2.4" then {
         allRefs = true;
       } else
@@ -476,7 +477,14 @@ in rec {
         "[opam-nix] a git dependency without an explicit sha1 is not supported in pure evaluation mode; try with --impure"
       else path;
 
-  fetchImpure = url: project:
+  # Rewrite a `git://` url into a `git+ssh` one
+  rewriteGitUrl = url:
+    if lib.strings.hasPrefix "git://" url then
+      "git+ssh://" + (builtins.substring 6 (-1) (builtins.replaceStrings [":"] ["/"] url))
+    else url;
+
+  fetchImpure = url_: project:
+    let url = rewriteGitUrl url_; in
     let splitUrl = splitString "+" (head (splitString ":" url)); in
     let proto = if length splitUrl > 1 then head splitUrl else null; in
     if proto == "git" then fetchGitURL url
```

**Additional context**

**Comment by balsoft** [comment]
I'm a bit confused; why add  `allRefs = true` when `ref` is also provided? Is there an example where this is needed?

**Comment by balsoft** [comment]
Also, it doesn't appear to be the correct behavior; technically, `git://` should use the old git protocol (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_git_protocol) and not ssh. That old protocol seems mostly unsupported nowadays, so maybe the `opam` files have to be updated to use something more modern?

**Comment by balsoft** [comment]
Also, it seems that it should actually work fine if the server you're trying to fetch from still supports the `git` protocol.

**Comment by thufschmitt** [comment]
> Also, it doesn't appear to be the correct behavior; technically, `git://` should use the old git protocol (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_git_protocol) and not ssh. That old protocol seems mostly unsupported nowadays, so maybe the `opam` files have to be updated to use something more modern?

Opam seems to drop the `git://` scheme, causing the url to be interpreted as the custom git-ssh urls (like `git@github.com:tweag/opam-nix.git`). So these aren't using the git protocol, but ssh.

**Comment by thufschmitt** [comment]
(regarding the fact that the `opam` files should be upgraded: I kinda agree in the abstract, but since Opam supports it, I guess `opam-nix` should too)

**Comment by balsoft** [comment]
> Opam seems to drop the git:// scheme, causing the url to be interpreted as the custom git-ssh urls (like git@github.com:tweag/opam-nix.git). So these aren't using the git protocol, but ssh.

Ah interesting. I tried to find a handler for it in the opam sources but can't for now. I'll implement it.

Also, what about the `allRefs` thing?

**Comment by thufschmitt** [comment]
[this](https://github.com/ocaml/opam/blob/3a1168051f58ec77e478ba4d3dc582d8be3abe55/src/core/opamUrl.ml#L106-L129) seems to be Opam logic for rewriting these URLs

**Comment by thufschmitt** [comment]
> Also, what about the allRefs thing?

That one is probably a leftover from debugging I accidentally committed :innocent:

**Comment by balsoft** [comment]
Hmm, I see. So the URL would look like `src: "git://git@github.com:tweag/opam-nix.git"` , correct?

In that case we can simplify the diff to:

```diff
diff --git a/src/evaluator/default.nix b/src/evaluator/default.nix
index de92f4e..508b181 100644
--- a/src/evaluator/default.nix
+++ b/src/evaluator/default.nix
@@ -450,7 +450,8 @@ in rec {
     let
       baseUrl = last (splitString "+" fullUrl); # Get rid of "git+"
       urlParts = splitString "#" baseUrl;
-      url = head urlParts;
+      rewriteGitUrl = replaceStrings ["git://"] [""]; # git:// URLs are interpreted as ssh by opam
+      url = rewriteGitUrl (head urlParts);
       ref = last urlParts;
       hasRef = length urlParts > 1;
       isRev = s: !isNull (builtins.match "[0-9a-f]{40}" s);
@@ -478,7 +479,7 @@ in rec {

   fetchImpure = url: project:
     let splitUrl = splitString "+" (head (splitString ":" url)); in
-    let proto = if length splitUrl > 1 then head splitUrl else null; in
+    let proto = if length splitUrl >= 1 then head splitUrl else null; in
     if proto == "git" then fetchGitURL url
     else if proto == "http" || proto == "https" then builtins.fetchTarball url
     # if no protocol assume a local file path
```

Because then the call would be `fetchGit { url = "git@github.com:tweag/opam-nix"; }` which seems to work just fine, no need for further rewriting

**Comment by balsoft** [comment]
Fixed in 5674bbcfea2341195e2f98cc1feb15d6db88b518

**Comment by thufschmitt** [comment]
> the call would be fetchGit { url = "git@github.com:tweag/opam-nix"; } which seems to work just fine, no need for further rewriting

Wow awesome!

For some reason I though this wasn't working. But it's just great if it does :)

**Comment by sir4ur0n** [comment]
@balsoft I think the commits you pushed to `main` do not have the same behavior as the patch I mentioned in [the first message](https://github.com/tweag/opam-nix/issues/99#issue-2666438931).

With our branch, our project's shell works; with latest `tweag/opam-nix`, it doesn't.
Unfortunately the error is related to versions of internal packages so I can't just copy/paste or show the project :neutral_face: 

I **suspect** this is related to `pin-depends` (in the `.opam` file) + transitive dependencies.

* We have this chain of dependencies: `A (internal) depends on B (internal), which depends on C (internal)`.
* `a.opam` specifies `pin-depends` for **both** `B` and `C`
* We provide a custom Opam repository to `buildOpamProject'` on top of the default one (`repos = [ opam-repository routine-opam-repository ];`), which contains a package for `C`

`B` should use the version of `C` from the `pin-depends` of `a.opam`, not the one from `routine-opam-repository`.

**Comment by balsoft** [comment]
Hmm, interesting. Is the error thrown during dependency fetching or version resolution? Is it different if you use `opam-nix` before 5674bbcfea2341195e2f98cc1feb15d6db88b518 without your patch?

**Comment by sir4ur0n** [comment]
> Hmm, interesting. Is the error thrown during dependency fetching or version resolution?

The error is
```
       error: builder for '/nix/store/qbkzags22mqq502qbwbfrx3c8idl5kgx-resolve.drv' failed with exit code 20;
       last 8 log lines:
       > [WARNING] Could not read file /nix/store/k4x4i713m89lnia09r6lrwmds44fhwa8-opam-repo/packages/color/color.0.3.0/opam. skipping:
       >           At /nix/store/k4x4i713m89lnia09r6lrwmds44fhwa8-opam-repo/packages/color/color.0.3.0/opam:37:5-37:6::
       >           Parse error
       > [ERROR] No solution including optional dependencies for <internal packages>:   * No agreement on the version of <E>:
       >             - A -> E < 0.1.0
       >             - A -> B >= 0.3.0 -> C -> D >= 0.20.0 -> E >= 0.1.0
       >
       >
       For full logs, run 'nix log /nix/store/qbkzags22mqq502qbwbfrx3c8idl5kgx-resolve.drv'.
```

So I assume it's during resolution? :sweat_smile: 

> Is it different if you use opam-nix before https://github.com/tweag/opam-nix/commit/5674bbcfea2341195e2f98cc1feb15d6db88b518 without your patch?

Yes, if I try with `tweag/opam-nix/c73f0cbd7f8541bd40613e6f401d8918dfea3fe9` I get this error:
```
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/c9wv7i0af6mysmy65x6nvyfw5izzxv4g-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'
         at /nix/store/c9wv7i0af6mysmy65x6nvyfw5izzxv4g-source/pkgs/stdenv/generic/make-derivation.nix:383:7:
          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: cannot coerce null to a string: null
```

**Comment by balsoft** [comment]
Actually, there was just a bug in my new fetcher implementation :) I mixed up URL query (`?foo=bar`) with the fragment (`#foobar`), and was just ignoring the rev if any was specified in the opam file. Can you try again with the latest version?

**Comment by sir4ur0n** [comment]
I am blocked by https://github.com/tweag/opam-nix/issues/100 to be able to confirm that it works :sweat_smile:

**Comment by sir4ur0n** [comment]
Everything seems to work fine now with the latest `main`, thank you @balsoft :pray:
